version: "3.9"

services:
  golang:
    container_name: golang
    build: 
      context: ../../
      dockerfile: tools/docker/golang.Dockerfile
    volumes:
      - ../../src/:/opt/go_home/
    entrypoint: ["/bin/sh", "-c","while true; do sleep 100; done;"]
  localstack:
    container_name: localstack
    build: 
      context: ../../
      dockerfile: tools/docker/localstack.Dockerfile
    ports:
      - '4566:4566'
    volumes:
      - ../../src/:/opt/localstack_home/
    environment:
      - DEBUG=true
      - DOCKER_HOST=unix:///var/run/docker.sock
  terraform:
    container_name: terraform
    build:
      context: ../../
      dockerfile: tools/docker/terraform.Dockerfile
    volumes:
      - ../../build/terraform/:/opt/tf_home/
    entrypoint: ["/bin/sh", "-c","while true; do sleep 100; done;"]