version: "3.9"

services:
  go-dev-container:
    container_name: golang
    build: 
      context: ../../
      dockerfile: tools/docker/Dockerfile
    volumes:
      - ../../src/:/opt/go_home/
    entrypoint: ["/bin/sh", "-c","while true; do sleep 100; done;"]
  localstack:
    container_name: localstack-container
    build: 
      context: ../../
      dockerfile: tools/docker/localstack.Dockerfile
    ports:
      - '4566:4566'
    environment:
      - DEBUG=true
      - DOCKER_HOST=unix:///var/run/docker.sock
  terraform:
    container_name: tf-local